addons:
  apt:
    sources:
      - sourceline: 'deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.6 multiverse'
        key_url: 'https://www.mongodb.org/static/pgp/server-3.6.asc'
    packages:
      mongodb-org-server
before_script:
  - sudo service mongod start
  - sleep 15
  - mongo admin --eval 'db.adminCommand( { setFeatureCompatibilityVersion:"3.6" } )'
language: node_js
node_js:
  - 8
  - 9
